version: '3.4'

services:
  blog:
    container_name: blog
    hostname: blog
    image: juliocesarmidia/blog:latest
    build:
      context: ./blog
    environment:
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017
    networks:
      - subnet_0
    restart: on-failure
    ports:
      - 50051:50051

  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo:5.0
    command: mongod --config /etc/mongo/mongod.conf --storageEngine wiredTiger
    environment:
      MONGO_INITDB_DATABASE: gogrpc
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - subnet_0
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db:rw
      - mongo-home:/home/mongodb:rw
      - ./mongo/mongod.conf:/etc/mongo/mongod.conf:ro
      - ./mongo/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./mongo/init.js:/init.js:ro

networks:
  subnet_0:
    driver: bridge

volumes:
  mongo-data: {}
  mongo-home: {}

secrets: {}
